apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: expense
data:
  DB_HOST : "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
spec:
  replicas: {{ .Values.deployment.replica}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: manjudbadevops/backend:{{ .Values.deployment.version }}
        envFrom:
        - configMapRef:
            name: myconfigmap
